# Generated by Django 4.2.5 on 2023-10-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hob_imag',
            field=models.CharField(default='https://www.shutterstock.com/image-vector/hobby-concept-music-video-game-260nw-1451106167.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_imag',
            field=models.CharField(default='https://www.library.yorku.ca/ds/wp-content/uploads/2021/07/digitalportfolio.png', max_length=500),
        ),
    ]
