4# Generated by Django 4.2.5 on 2023-10-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_hob_imag_portfolio_port_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_id', models.IntegerField()),
                ('cont_name', models.CharField(max_length=200)),
                ('cont_email', models.CharField(max_length=200)),
                ('cont_message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hob_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
